version: '3.0'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
      - ./:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
  enigma:
    image: z0rr0/enigma:latest
    volumes:
       - ./:/data/conf
    ports:
      - "18080:18080"
    links:
      - redis:redis
    restart: always
